### ISSUE TITLE
compute time

### ISSUE THREAD

**Issue by wangjunhe8127** [motional/nuplan-devkit#135]
*Ex. What is a lane connector? or How many wheels do your vehicles have?*
hi, i want to know the save files' time is in the final compute time?
beacause i see the simulation code compute much time ,and some are generate by save files ,so i want to know the answer.thanks!

**Comment by michael-motional** [comment]
If you're wondering about how much time saving the SimulationLogs to disk adds to the simulation runtime, you can disable the [callback](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/simulation/callback/simulation_log_callback.py) by setting `callback: null` [here](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/script/config/simulation/default_simulation.yaml#L18).

Let me know if that answers your question!

**Comment by wangjunhe8127** [comment]
> If you're wondering about how much time saving the SimulationLogs to disk adds to the simulation runtime, you can disable the [callback](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/simulation/callback/simulation_log_callback.py) by setting `callback: null` [here](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/script/config/simulation/default_simulation.yaml#L18).
> 
> Let me know if that answers your question!

yeah,it seems like when test the time final in competition ,the callback will be set null?

**Comment by gianmarco-motional** [comment]
@wangjunhe8127 Your compute time budget is only how long it takes to perform the [gRPC call ](https://github.com/motional/nuplan-devkit/blob/d1d654e1df30e3ac5ac1690c3240a09a18fe4d66/nuplan/planning/simulation/planner/remote_planner.py#L226)to your planner.
You can test this by running locally with docker-compose.

Otherwise if you are just running using thr `run_simulation` script, what you care about is how long it takes to compute `<your_planner>.compute_trajectory()`. This is timed by default and you can find the values in `runner_report.parquet`; which is in your output directory of the simulation.

If you still have doubts, feel free to reopen the issue!
