### ISSUE TITLE
agents' future traj?

### ISSUE THREAD

**Issue by wangjunhe8127** [motional/nuplan-devkit#155]
Ex, Can we get the agents's traj in future when training.

**Comment by wangjunhe8127** [comment]
I mean：can we get agents' feature using agent_build in **closed loop**?

**Comment by christopher-motional** [comment]
Hi @wangjunhe8127, sorry for the delayed response. You can find future trajectories in the [predictions](https://github.com/motional/nuplan-devkit/blob/master/nuplan/common/actor_state/agent.py#L26) data member of agents when available, however this is only supplied during training when ground truth is available from the scenario. Such future information is not available during simulation, closed loop or otherwise.
