### ISSUE TITLE
How are displacement errors calculated in (open loop) simulation

### ISSUE THREAD

**Issue by mh0797** [motional/nuplan-devkit#166]
Hi,

The following may be a bug, but since i am not sure i will first put it here as question.

I noticed the displacement errors obtained by open loop evaluation, do not match with common ADE and FDE metrics.
For comparison I did an open loop simulation and compared the ADE/FDE for each scenario with an own evaluation which simply calculates ADE/FDE by extracting the ground truth future trajectory from the scenario and comparing it to the models output.

Details:
- The model uses a prediction horizon of 8s. Therefore, I obtained the ADE/FDE from the simulation from the  `planner_expert_ADE_horizon_8_stat_value` and `planner_expert_FDE_horizon_8_stat_value` columns in the metrics parquet file 
- My ADE/FDE implementation looks as follows:
```
def eval_XDE(prediction: Trajectory, gt: Trajectory, x: str) -> torch.Tensor:
    DE = torch.linalg.norm(
        (prediction.data - gt.data), 
        ord=2, 
        dim=-1
    )
    if x=="ADE":
        return DE.mean()
    elif x=="FDE":
        return DE[...,-1].mean()
```
- I used the exact same scenarios and the exact same model as in the simulation.

Can you clarify, if this is a bug in the simulation or if I am doing something wrong?

**Comment by noushin-motional** [comment]
Hello @mh0797, thanks for your question! 
You can find the description of the metrics calculations [here](https://github.com/motional/nuplan-devkit/blob/master/docs/metrics_description.md). The ADE/FDE errors are calculated over down-sampled trajectories with a frequency of 1 Hz and over 3 different time horizons in future (3,5,8s) so that all submissions are compared at the same samples. The errors in the planner_expert_ADE_horizon_{3/5/8}_stat_value are generated following this [code](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/metrics/evaluation_metrics/common/planner_expert_average_l2_error_within_bound.py) , to compare the results with your implementation, you need to ensure the same samples are used with 1s interval, and note that  since in open-loop the errors at current sample is 0, we remove that and only consider samples in future within the selected horizon (See how [expert] (https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/metrics/evaluation_metrics/common/planner_expert_average_l2_error_within_bound.py#L110) and [planner](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/metrics/evaluation_metrics/common/planner_expert_average_l2_error_within_bound.py#L116) trajectories are compared)

**Comment by mh0797** [comment]
Hello @noushin-motional,
thank you for the clarification. However, in that case at least the FDE should be equal, which is not the case.
Is this a potential bug or am i missing something?

**Comment by noushin-motional** [comment]
Hello @mh0797, I don't find any bugs in the code or your implementation, my guess is that you might be finding errors at different sampled timestamps or there can be some small difference due to interpolation of trajectories. How large is the difference between the two error values? Can you please share how you're extracting the ground truth future trajectory from the scenario? What's the frequency of your planner? If you can provide more info that we can re-create your issue that would be great!

**Comment by mh0797** [comment]
Hello @noushin-motional,
In my opinion the error is way too large to result from the interpolation. For instance, I evaluated several models with ADE ~2m and FDE ~5m and the ADE and FDE calculated in the simulation are ~15m and ~40m respectively.

I get the ground truth future trajectory using the provided `EgoTrajectoryTargetBuilder`. My planner has a future time horizon of 8s sampled with 8 future poses. Maybe it makes sense to just look at the FDE first, since interpolation should have no impact on it. 

### Details
I evaluated this in the following way. First i ran the open loop simulation:
```
python ~/nuplan/nuplan-devkit/nuplan/planning/script/run_simulation.py \
+simulation=open_loop_boxes \
ego_controller=log_play_back_controller \
observation=box_observation \
planner=ml_planner \
model=my_model\
planner.ml_planner.model_config="\${model}" \
planner.ml_planner.checkpoint_path=$CHECKPOINT_PATH \
experiment_name=$EXPERIMENT_NAME \
scenario_filter.remove_invalid_goals=true \
scenario_filter.num_scenarios_per_type=10 \
model.past_trajectory_sampling.time_horizon=1.9 \
metric_aggregator.open_loop_boxes_weighted_average.challenge_name=null \
```

then I loaded the metrics file `planner_expert_final_l2_error_within_bound.parquet`. I obtained the mean FDE for the simulation by simply taking the mean of the column `planner_expert_FDE_horizon_8_stat_value` (Note: my planner has an horizon of 8s).

The I took the list of simulation scenarios from the columns `log_name` and `scenario_name`. For all these scenarios I generated the ground-truth future using the `EgoTrajectoryTargetBuilder` as well as the prediction by infering my trained model. I compared both using the simple code above, obtaining the FDE (and ADE). Finally, I evaluated the mean FDE (and ADE) across all simulation scenarios and compared it to the one returned by the simulation.

**Comment by noushin-motional** [comment]
Thanks @mh0797 for the details! Yes the difference doesn't seem like is due to interpolations.The simulation open-loop metrics compute the L2 error between the expert and proposed trajectory in global coordinates (absolute states), however, the `EgoTrajectoryTargetBuilder` returns the relative expert states in ego frame used during the training and the planner output returns the absolute states. Could you try using [scenario.get_ego_future_trajectory](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/scenario_builder/nuplan_db/nuplan_scenario.py#L299) and find the errors? 
You can also check the **time_series_timestamps** and **time_series_selected_frames** to make sure you're finding the errors at the same samples for each scenario, for instance, time_series_selected_frames = [0, 10, 20, ..., 140, 150]. Let's consider the first frame, iteration = 0, you need to find FDE between your planner final absolute center pose and expert absolute center pose at frame 80 (assuming your planner as 8s horizon). This error would show the FDE at frame 0, the same process is done for all frames in time_series_selected_frames, and in the end the mean of these FDEs is reported for **planner_expert_FDE_horizon_8_stat_value** for the given scenario in planner_expert_average_l2_error_within_bound.parquet file.

**Comment by mh0797** [comment]
Hi @noushin-motional,
In my example I just calculated the displacement errors based on the model output and the corresponding target. Therefore, for every scenario only iteration = 0 is evaluated (feature builders and target builders select only this one). 

Hence, I think it is a good idea to compare the FDE of the exact same frames for all scenarios. However, I am not sure how I can infer my model for these intermediate frames, as I cannot obtain features for iterations other than 0. Can you give me a hint on how to do that?
