### ISSUE TITLE
Question about nuplan_scenario_visualization.ipynb

### ISSUE THREAD

**Issue by IvanChen777** [motional/nuplan-devkit#168]
Hi, I have a problem regarding the nuplan_scenario_visualization.ipynb file, it seems that this file could run well both in vscode and in jupyter notebook. However, the result could not be displayed. Do you know why? Thank you in advance!
<img width="1557" alt="截屏2022-10-22 12 11 44" src="https://user-images.githubusercontent.com/91310432/197333728-08a9c6af-c58f-43f0-816d-3dc1c47eb026.png">

**Comment by michael-motional** [comment]
Hey @IvanChen777, currently there are two problems with the notebook:

- the visualization doesn't work correctly over ssh, due to a port forwarding issue (bokeh starts a server on a random port for its visualization, and the request from the notebook doesn't make it to the server) -- if you're running on a remote machine, I'd try [this](https://github.com/motional/nuplan-devkit/issues/118#issuecomment-1265968365) workaround for now.
- running the notebook on a port other than 8888 causes an error -- this doesn't seem the be happening in your case

lastly, note that the notebook doesn't render a scenario immediately -- only after you select a new option from the drop-down

**Comment by IvanChen777** [comment]
Hi, @michael-motional , thank you for your suggestions, I will try your methods, and hope it work:)

**Comment by michael-motional** [comment]
Closing -- this is fixed in the coming release
