### ISSUE TITLE
use for prediction

### ISSUE THREAD

**Issue by winckrc** [motional/nuplan-devkit#20]
Is the dataset similar enough to nuscenes to be used for prediction?

**Comment by holger-motional** [comment]
Hi. Apologies for the delay. nuPlan is conceptually similar to nuScenes, but the code is not compatible. Rather than trying to write adapters to nuScenes, we will create a nuPlan smart agent challenge in the second half of 2022. This challenge is basically similar to a prediction challenge, except for the metrics and potential evaluation in closed loop.

**Comment by dougefla** [comment]
> Hi. Apologies for the delay. nuPlan is conceptually similar to nuScenes, but the code is not compatible. Rather than trying to write adapters to nuScenes, we will create a nuPlan smart agent challenge in the second half of 2022. This challenge is basically similar to a prediction challenge, except for the more sophisticated metrics and potential evaluation in closed loop.

Hi, thank you for your explaining. But I wonder if this challenge you mentioned created in the second half of 200 is the same one as mentioned in nuPlan official website "benchmark challenges starting in Q2 2022"? Is the schedule changed? Appreciate any reply.

**Comment by holger-motional** [comment]
Yes. The first challenge will start mid April and run until June, with the results being presented at CVPR 2022.

**Comment by dougefla** [comment]
> Yes. The first challenge will start mid April and run until June, with the results being presented at CVPR 2022.

I see. Thank you for your quick reply!
