### ISSUE TITLE
How to access raw camera/lidar data ?

### ISSUE THREAD

**Issue by sindhu-pr** [motional/nuplan-devkit#218]
I am using NuPlanDB to access raw image data whose filenames are provided in image table of the .db files in  trainval as well as mini sets. Specifically, I am using the get() functions like `get_test_nuplan_image(), get_test_nuplan_lidarpc_with_blob()` defined in **_nuplan/database/tests/nuplan_db_test_utils.py_** for accessing the images. These functions try to access blobs given some default indices. 

The comments in this .py file say that sensor blobs are not yet supported. I would like to know by when will the sensor blobs be supported. Same holds for lidar raw data as well. Unable to access these as well. Will these ever be supported ? Since the nuPlan challenge is up and it asks for ML-based planner submissions, I would have expected these to be supported. 

Thanks,
Sindhu

**Comment by patk-motional** [comment]
Hi @sindhu-pr,

Unfortunately, we are not supporting sensor-to-trajectory (end-to-end) planners for the competition. The competition will only feature detections-to-trajectory.

We are working on releasing the sensor data very soon. There has been some delays due to the sheer size of the sensor data set. We will make an announcement both here and through our newsletter once it is released.

Thank you for your patience

**Comment by stephenjia** [comment]
@patk-motional Hi, could I ask when you plan to release the raw data? Or do you still plan to release them?
