### ISSUE TITLE
 Submission code runs too long without results

### ISSUE THREAD

**Issue by MCZhi** [motional/nuplan-devkit#283]
Hi there,

I have submitted my code to the EvalAI server for evaluation. However, the submission has been running for over one day now, and I have not received any results yet. I'm not sure if this is due to an issue with my code, or if there is some other problem with the submission process. Could you please help me troubleshoot this issue?

Thank you for your help!

**Comment by patk-motional** [comment]
Hi @MCZhi,

What is your submission no. we can take a look?

**Comment by MCZhi** [comment]
Hi @patk-motional,

Thank you for your help! I couldn't find the exact submission number, but my team name is AID and the submitted file says {"submitted_image_uri": "937891341272.dkr.ecr.us-east-1.amazonaws.com/nuplan-planning-challenge-1856-participant-team-19955:963e06d9-33b0-41ca-8bfa-8ddb7599d309"}. Hope this information is helpful.

**Comment by patk-motional** [comment]
Yes, thank you. I'll get back to you shortly

**Comment by gianmarco-motional** [comment]
Hello,

There was a problem with an update on AWS side. We are landing a fix soon and will retrigger the submissions afterwards.

Sorry for the inconvenience,
Gianmarco

**Comment by JingyuQian** [comment]
Hello @gianmarco-motional , we encountered the same problem, and the submission failed. We're not sure whether the failure is due to submission retriggering or our model. Our submission detail is:
{"submitted_image_uri": "937891341272.dkr.ecr.us-east-1.amazonaws.com/nuplan-planning-challenge-1856-participant-team-19110:cb1692f7-76c1-466c-ad3a-dbf3b4fb9d17"}

Could you kindly take a look for us?

**Comment by patk-motional** [comment]
Hi @JingyuQian,

It seems that your submission container took too long to produce a trajectory.
https://evalai.s3.amazonaws.com/media/submission_files/submission_275329/1bccb59a-1832-4e5b-8134-d579a4944a8a.txt
