### ISSUE TITLE
Submission pipeline: Too much time for pip install

### ISSUE THREAD

**Issue by bulbcult** [motional/nuplan-devkit#286]
When I am trying to run the command for submission: `docker build --network host -f Dockerfile.submission . -t nuplan-evalservice-server:test.contestant`, I encounter two issues:

1. `Sending build context to Docker daemon 68GB` --> takes a lot of time (about 1 hour).
     Question: Is this common?
3. When the Dockerfile.submission runs to `RUN conda env create -f $NUPLAN_HOME/environment_submission.yml`, it takes forever to exert`Installing pip dependencies`. 
     Question: How can I resolve this? The terminal just freeze at`Installing pip dependencies...` for 4 and more hours.

Thank you for any helpful insights!

**Comment by JingyuQian** [comment]
@bulbcult 
A1: the command uses "." as the build context, which I assume is the `nuplan-devkit` folder. Try to keep only the necessary in your `nuplan-devkit` folder, otherwise all contents below the `nuplan-devkit` will be sent to Docker daemon.
A2: yes, takes a lot of time. Solved it by specifying specific versions of libraries in `requirements.txt`.

**Comment by bulbcult** [comment]
> @bulbcult A1: the command uses "." as the build context, which I assume is your `nuplan-devkit` folder. Try to keep only the necessary in your `nuplan-devkit` folder, otherwise all contents below the `nuplan-devkit` will be sent to Docker daemon. A2: yes, takes a lot of time. Solved it by specifying specific versions of libraries in `requirements.txt`.

Thank you mate, that helps me a lot!!
