### ISSUE TITLE
Questions about competition rules regarding the input, model ..etc

### ISSUE THREAD

**Issue by polcomicepute** [motional/nuplan-devkit#324]
Questions about competition rules regarding the input, model ..etc

1. Can I define the input for the ml planner used in the competition according to my own preferences by creating feature and feature builder python codes (model too) to submit? 
Should these files be composed of Python files like feature, builder, model, etc. and yaml(config) ?

2. I'm also curious about the path to store these files to submit. 
Is it the same as the paths used for features and models in the existing nuplan-devkit, or should I put them in a specific folder within the Docker container? I've been finding related documentations, but I'm unsure about the exact information.

**I know that the competition has already ended**, but I'm asking these questions because I'm curious about manipulating data within a certain range to use as input for future competitions and benchmarks.

Thank you.

**Comment by patk-motional** [comment]
Hi @polcomicepute,

1. I've answered a similar question in the past https://github.com/motional/nuplan-devkit/issues/138#issuecomment-1263064590. Feel free to ask any follow up questions.
2. You can include anything in your docker image. `Docker.submission` is setup so that everything is relative to [NUPLAN_HOME](https://github.com/motional/nuplan-devkit/blob/master/Dockerfile.submission#L29). Hence, if you add new code inside `nuplan-devkit/` it should be automatically included in the docker image.

**Comment by polcomicepute** [comment]
Then, Would modifying and utilizing the code that generates scenarios and creates features from the scenario builder, filter, and similar components sourced from a database not violate the competition rules?

Thank you.

**Comment by patk-motional** [comment]
No not at all. We are not running the simulation code included in your submission image. We have a copy of the current master in our submission server.
