### ISSUE TITLE
Extracting the raster map of a scenario

### ISSUE THREAD

**Issue by pegah-kh** [motional/nuplan-devkit#357]
Hello,

I am trying to extract the drivable area map of a scenario, using the function [get_raster_map_layer](https://github.com/motional/nuplan-devkit/blob/cd3fd8d3d0c4d390fcb74d05fd56f92d9e0c366b/nuplan/common/maps/nuplan_map/nuplan_map.py#L103), and then simply draw the agents on top of it (using the transform matrix provided with the data map and the resolution).
However, by doing transform@agent_coord*resolution and extracting the map around the coordinate of ego (at the beginning of the scenario), I am unable to have the same map as observed in nuboard for a specific scenario. Is it the right way of projecting the coordinates back to the map space and if not what can be the problem?  SOLVED :))

**Comment by Jiale-Fan** [comment]
Hello, 

I'm having the same confusion. In my opinion transform@current_ego_position should give the ego position in pixel coordinates, and (transform@current_ego_position)/precision should give the indices of the raster, which have to be non-negative. But it turns out to be negative sometimes so I'm so confused. Could you tell me how you managed to find the correct way to project? I would appreciate it so much!
