### ISSUE TITLE
Resolution of BaselinePath

### ISSUE THREAD

**Issue by mh0797** [motional/nuplan-devkit#89]
Hi,

can you tell me the resolution (in m) of the discretized baselinepaths of the maps (accessed via MapObject.baseline_path.discrete_path) ?
Is there a way to control the resolution of the discretization?

Thank you

**Comment by patk-motional** [comment]
Hi @mh0797,

There is no way to control the resolution currently, the coordinates are pulled from the underlying map data frame. The resolution is also not now available there either. The resolution varies from one baseline to another as well (2cm - 30cm).

One thing that is commonly done is to create either a [path](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/simulation/path/interpolated_path.py) or [trajectory](https://github.com/motional/nuplan-devkit/blob/master/nuplan/planning/simulation/trajectory/interpolated_trajectory.py) in order to sample of it w.r.t. to progress or time respectively
A discrete_path function that accepts a resolution could be  built into the map interface directly but I rather the user take care of this themselves

**Comment by mh0797** [comment]
Hi,
thanks for the information. I guess using interpolated path is ok for now but i would suggest to add the opportunity to control the resolution into the map interface.

I will close this issue since the question is answered.

Thank you!
